name: Release

on:
  workflow_run:
    workflows: ['Main']
    branches: [main]
    types:
      - completed

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

permissions: {}

jobs:
  release:
    if: github.event.workflow_run.conclusion == 'success'
    name: Release
    permissions:
      attestations: write # to create attestations (changesets/action)
      contents: write # to create the release (changesets/action)
      id-token: write # for npm provenance verification (changesets/action)
      issues: write # to post issue comments (changesets/action)
      pull-requests: write # to create the pull request (changesets/action)
    # Pinned from benhigham/.github main branch, 2026-03-04
    uses: benhigham/.github/.github/workflows/release-changesets.yml@7a1eb9105ae462853ee01a41ad45518b4bae51c9
    with:
      node-version: 22
